const { withAppBuildGradle } = require('expo/config-plugins');

/**
 * Pins `ndk.debugSymbolLevel` to `NONE` on the release build type.
 *
 * `android/` is generated by `expo prebuild` on every build and is not checked
 * in, so this edit lives in a config plugin instead of a hand-edited
 * `android/app/build.gradle`.
 *
 * AGP already defaults to `none`, so this does not change the size of a release
 * APK (its native libraries are stripped either way). What it guarantees is that
 * no native debug metadata is ever packaged: without it, raising the level later
 * would silently add a `native-debug-symbols.zip` to an AAB.
 */
const RELEASE_BUILD_TYPE = /(buildTypes\s*\{[\s\S]*?\brelease\s*\{)/;

const NDK_BLOCK = `
            // Release packaging carries no native debug metadata.
            ndk {
                debugSymbolLevel 'NONE'
            }`;

module.exports = function withAndroidDebugSymbolLevel(config) {
  return withAppBuildGradle(config, (config) => {
    const { contents, language } = config.modResults;

    if (language !== 'groovy') {
      throw new Error(
        `withAndroidDebugSymbolLevel: expected a Groovy build.gradle, received "${language}"`
      );
    }

    // Prebuild can run on top of an existing native project, so stay idempotent.
    if (contents.includes('debugSymbolLevel')) {
      return config;
    }

    if (!RELEASE_BUILD_TYPE.test(contents)) {
      throw new Error(
        'withAndroidDebugSymbolLevel: no release build type found in android/app/build.gradle'
      );
    }

    // Insert as the first statement of the release block, after its opening brace.
    config.modResults.contents = contents.replace(RELEASE_BUILD_TYPE, (block) => block + NDK_BLOCK);

    return config;
  });
};
